# Generated by Django 6.0.1 on 2026-01-25 08:29

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('address_id', models.UUIDField(db_column='ADDRESS_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('entity_id', models.UUIDField(blank=True, db_column='ENTITY_ID', null=True)),
                ('entity_type', models.TextField(blank=True, db_column='ENTITY_TYPE', null=True)),
                ('street', models.TextField(blank=True, db_column='STREET', null=True)),
                ('city', models.TextField(blank=True, db_column='CITY', null=True)),
                ('postal_code', models.TextField(blank=True, db_column='POSTAL_CODE', null=True)),
                ('country', models.TextField(blank=True, db_column='COUNTRY', null=True)),
            ],
            options={
                'db_table': 'ADDRESS_BOOK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BranchStation',
            fields=[
                ('station_id', models.UUIDField(db_column='STATION_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='NAME')),
                ('mac_address', models.TextField(blank=True, db_column='MAC_ADDRESS', null=True)),
                ('last_sync', models.DateTimeField(blank=True, db_column='LAST_SYNC', null=True)),
            ],
            options={
                'db_table': 'BRANCH_STATIONS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.UUIDField(db_column='CURRENCY_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.TextField(db_column='CODE')),
                ('name', models.TextField(blank=True, db_column='NAME', null=True)),
                ('symbol', models.TextField(blank=True, db_column='SYMBOL', null=True)),
            ],
            options={
                'db_table': 'CURRENCIES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('rate_id', models.UUIDField(db_column='RATE_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(db_column='RATE', decimal_places=6, max_digits=18)),
                ('effective_date', models.DateField(blank=True, db_column='EFFECTIVE_DATE', default=django.utils.timezone.localdate, null=True)),
            ],
            options={
                'db_table': 'CURRENCY_RATES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.UUIDField(db_column='LOCATION_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='NAME')),
                ('address', models.TextField(blank=True, db_column='ADDRESS', null=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
            ],
            options={
                'db_table': 'LOCATIONS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('subsidiary_id', models.UUIDField(db_column='SUBSIDIARY_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='NAME')),
                ('tax_number', models.TextField(blank=True, db_column='TAX_NUMBER', null=True)),
                ('commercial_registration', models.TextField(blank=True, db_column='COMMERCIAL_REGISTRATION', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='CREATED_AT', default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'SUBSIDIARIES',
                'managed': False,
            },
        ),
    ]
