# Generated by Django 6.0.1 on 2026-02-09 08:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FndLov',
            fields=[
                ('lov_id', models.UUIDField(db_column='LOV_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.TextField(db_column='CODE')),
                ('name', models.TextField(blank=True, db_column='NAME', null=True)),
            ],
            options={
                'db_table': 'FND_LOVS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FndLovValue',
            fields=[
                ('value_id', models.UUIDField(db_column='VALUE_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, db_column='VALUE', null=True)),
                ('label', models.TextField(blank=True, db_column='LABEL', null=True)),
            ],
            options={
                'db_table': 'FND_LOVS_VALUES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.UUIDField(db_column='ITEM_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item_code', models.TextField(db_column='ITEM_CODE')),
                ('item_name', models.TextField(db_column='ITEM_NAME')),
                ('barcode', models.TextField(blank=True, db_column='BARCODE', null=True)),
                ('description', models.TextField(blank=True, db_column='DESCRIPTION', null=True)),
                ('is_taxable', models.BooleanField(db_column='IS_TAXABLE', default=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='CREATED_AT', default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'ITEMS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('category_id', models.UUIDField(db_column='CATEGORY_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='NAME')),
            ],
            options={
                'db_table': 'ITEM_CATEGORY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPriceList',
            fields=[
                ('price_list_id', models.UUIDField(db_column='PRICE_LIST_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('price', models.DecimalField(db_column='PRICE', decimal_places=2, max_digits=12)),
                ('start_date', models.DateField(blank=True, db_column='START_DATE', null=True)),
                ('end_date', models.DateField(blank=True, db_column='END_DATE', null=True)),
            ],
            options={
                'db_table': 'ITEM_PRICE_LIST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('unit_type_id', models.UUIDField(db_column='UNIT_TYPE_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='NAME', null=True)),
            ],
            options={
                'db_table': 'UNITS_TYPE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('uom_id', models.UUIDField(db_column='UOM_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='NAME')),
                ('code', models.TextField(blank=True, db_column='CODE', null=True)),
            ],
            options={
                'db_table': 'UOM',
                'managed': False,
            },
        ),
    ]
