"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import importlib.util
from pathlib import Path
from urllib.parse import unquote, urlparse

from corsheaders.defaults import default_headers

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
if load_dotenv:
    override_env = os.environ.get("ENV_FILE")
    if override_env:
        override_path = Path(override_env)
        if not override_path.is_absolute():
            override_path = BASE_DIR / override_path
        if override_path.exists():
            load_dotenv(override_path)
    else:
        env_path = BASE_DIR / ".env"
        if env_path.exists():
            load_dotenv(env_path)
        else:
            alt_env_path = BASE_DIR / ".env.pos"
            if alt_env_path.exists():
                load_dotenv(alt_env_path)


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_int(name, default=0):
    value = os.environ.get(name)
    if value is None or value.strip() == "":
        return default
    return int(value)


def env_list(name, default=None):
    value = os.environ.get(name)
    if value is None:
        return default if default is not None else []
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "unsafe-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", False)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", ["pos-system-ciq8.onrender.com","localhost", "127.0.0.1"])

if not DEBUG and SECRET_KEY == "unsafe-change-me":
    raise RuntimeError("DJANGO_SECRET_KEY must be set when DEBUG is False.")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'core',
    'tenants',
    'security',
    'catalog',
    'inventory',
    'customers',
    'taxes',
    'transactions',
    'accounting',
    'reporting',
    'pos',
    'config_engine',
    'sync_engine',
    'workflow',
]

HAS_CHANNELS = importlib.util.find_spec("channels") is not None
HAS_CHANNELS_REDIS = importlib.util.find_spec("channels_redis") is not None
if HAS_CHANNELS:
    INSTALLED_APPS.append("channels")
if importlib.util.find_spec("drf_spectacular") is not None:
    INSTALLED_APPS.append("drf_spectacular")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LOG_DB_QUERIES = env_bool("DJANGO_LOG_DB", False)
if LOG_DB_QUERIES:
    MIDDLEWARE.insert(0, "core.middleware.ForceDebugCursorMiddleware")

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
if HAS_CHANNELS:
    ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


def parse_database_url(database_url):
    parsed = urlparse(database_url)
    if parsed.scheme not in {"postgres", "postgresql"}:
        raise RuntimeError("DATABASE_URL must use postgres or postgresql.")
    return {
        "NAME": parsed.path.lstrip("/"),
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or "5432"),
    }


DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
DB_ENGINE = os.environ.get("DB_ENGINE", "django.db.backends.postgresql").strip()

if DB_ENGINE != "django.db.backends.postgresql":
    raise RuntimeError(
        "Only PostgreSQL is supported. Set DB_ENGINE=django.db.backends.postgresql."
    )

if DATABASE_URL:
    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            **parse_database_url(DATABASE_URL),
            "CONN_MAX_AGE": env_int("DB_CONN_MAX_AGE", 60),
            "OPTIONS": {
                "connect_timeout": env_int("DB_CONNECT_TIMEOUT", 10),
            },
        }
    }
else:
    db_name = os.environ.get("DB_NAME", "").strip()
    if not db_name:
        raise RuntimeError(
            "DB_NAME is required when DATABASE_URL is not set (PostgreSQL only)."
        )
    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            "NAME": db_name,
            "USER": os.environ.get("DB_USER", "").strip(),
            "PASSWORD": os.environ.get("DB_PASSWORD", "").strip(),
            "HOST": os.environ.get("DB_HOST", "localhost").strip(),
            "PORT": os.environ.get("DB_PORT", "5432"),
            "CONN_MAX_AGE": env_int("DB_CONN_MAX_AGE", 60),
            "OPTIONS": {
                "connect_timeout": env_int("DB_CONNECT_TIMEOUT", 10),
            },
        }
    }

sslmode = os.environ.get("DB_SSLMODE")
if sslmode:
    DATABASES["default"]["OPTIONS"]["sslmode"] = sslmode

options_parts = []
db_schema = os.environ.get("DB_SCHEMA", "pos_loc").strip() or "pos_loc"
options_parts.append(f"-c search_path={db_schema}")

statement_timeout = os.environ.get("DB_STATEMENT_TIMEOUT_MS")
if statement_timeout:
    options_parts.append(f"-c statement_timeout={statement_timeout}")

if options_parts:
    DATABASES["default"]["OPTIONS"]["options"] = " ".join(options_parts)

if not DATABASES["default"].get("NAME"):
    raise RuntimeError("DB_NAME is required for PostgreSQL.")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = env_bool("DJANGO_CORS_ALLOW_ALL", False)
CORS_ALLOW_CREDENTIALS = env_bool("DJANGO_CORS_ALLOW_CREDENTIALS", True)
CORS_ALLOWED_ORIGINS = env_list("DJANGO_CORS_ALLOWED_ORIGINS", [])
CORS_ALLOW_HEADERS = tuple(default_headers) + ("x-device-token",)
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", [])

DEFAULT_SCHEMA_CLASS = "rest_framework.schemas.openapi.AutoSchema"
if importlib.util.find_spec("drf_spectacular") is not None:
    DEFAULT_SCHEMA_CLASS = "drf_spectacular.openapi.AutoSchema"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": DEFAULT_SCHEMA_CLASS,
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": env_int("DJANGO_PAGE_SIZE", 50),
}

REDIS_URL = (os.environ.get("REDIS_URL") or "").strip()
if HAS_CHANNELS and HAS_CHANNELS_REDIS and REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        }
    }
elif HAS_CHANNELS:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }

SPECTACULAR_SETTINGS = {
    "TITLE": "POS API",
    "DESCRIPTION": "Offline-first Restaurant POS APIs",
    "VERSION": "1.0.0",
}

POS_PUBLIC_API_READ = env_bool("DJANGO_PUBLIC_API_READ", DEBUG)
POS_PUBLIC_API_WRITE = env_bool("DJANGO_PUBLIC_API_WRITE", DEBUG)
POS_ERP_API_KEY = os.environ.get("POS_ERP_API_KEY", "").strip()
WHATSAPP_ENABLED = env_bool("WHATSAPP_ENABLED", False)
WHATSAPP_ACCESS_TOKEN = os.environ.get("WHATSAPP_ACCESS_TOKEN", "").strip()
WHATSAPP_PHONE_NUMBER_ID = os.environ.get("WHATSAPP_PHONE_NUMBER_ID", "").strip()
WHATSAPP_API_URL = os.environ.get("WHATSAPP_API_URL", "https://graph.facebook.com/v19.0").strip()
WHATSAPP_TEMPLATE_LANGUAGE = os.environ.get("WHATSAPP_TEMPLATE_LANGUAGE", "ar").strip() or "ar"
WHATSAPP_TEMPLATE_ORDER_CREATED = os.environ.get("WHATSAPP_TEMPLATE_ORDER_CREATED", "").strip()
WHATSAPP_TEMPLATE_ORDER_STATUS = os.environ.get("WHATSAPP_TEMPLATE_ORDER_STATUS", "").strip()
WHATSAPP_DEFAULT_COUNTRY_CODE = os.environ.get("WHATSAPP_DEFAULT_COUNTRY_CODE", "").strip()
WHATSAPP_WEBHOOK_VERIFY_TOKEN = os.environ.get("WHATSAPP_WEBHOOK_VERIFY_TOKEN", "").strip()

LOG_DIR = os.environ.get("POS_LOG_DIR")
if not LOG_DIR:
    program_data = os.environ.get("ProgramData") or os.environ.get("PROGRAMDATA")
    if program_data:
        LOG_DIR = os.path.join(program_data, "POS System", "logs")
    else:
        LOG_DIR = str(BASE_DIR / "logs")

try:
    os.makedirs(LOG_DIR, exist_ok=True)
except OSError:
    LOG_DIR = str(BASE_DIR / "logs")
    os.makedirs(LOG_DIR, exist_ok=True)

LOG_LEVEL = os.environ.get("DJANGO_LOG_LEVEL", "INFO").strip().upper()
LOG_CONSOLE = env_bool("DJANGO_LOG_CONSOLE", True)
LOG_FILE = env_bool("DJANGO_LOG_FILE", True)

log_handlers = {
    "db_file": {
        "class": "logging.FileHandler",
        "filename": os.path.join(LOG_DIR, "db.log"),
        "level": "DEBUG",
        "formatter": "verbose",
        "encoding": "utf-8",
    },
}

if LOG_CONSOLE:
    log_handlers["console"] = {
        "class": "logging.StreamHandler",
        "level": LOG_LEVEL,
        "formatter": "verbose",
    }

if LOG_FILE:
    log_handlers["app_file"] = {
        "class": "logging.FileHandler",
        "filename": os.path.join(LOG_DIR, "app.log"),
        "level": LOG_LEVEL,
        "formatter": "verbose",
        "encoding": "utf-8",
    }

root_handlers = []
if LOG_CONSOLE:
    root_handlers.append("console")
if LOG_FILE:
    root_handlers.append("app_file")

db_handlers = ["db_file"]
if LOG_DB_QUERIES and LOG_CONSOLE:
    db_handlers.append("console")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": log_handlers,
    "root": {
        "handlers": root_handlers,
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django.db.backends": {
            "handlers": db_handlers,
            "level": "DEBUG" if LOG_DB_QUERIES else "WARNING",
            "propagate": False,
        },
    },
}

SILENCED_SYSTEM_CHECKS = ["fields.W342"]

SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", not DEBUG)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SECURE_HSTS_SECONDS = env_int("DJANGO_SECURE_HSTS_SECONDS", 3600 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", not DEBUG)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

SECURE_PROXY_SSL_HEADER = None
if env_bool("DJANGO_SECURE_PROXY_SSL_HEADER", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
