# Generated by Django 6.0.2 on 2026-02-18 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entitysyncversion',
            new_name='sync_engine_branch__32c5bf_idx',
            old_name='sync_engine__branch__f2606c_idx',
        ),
        migrations.RenameIndex(
            model_name='syncconflict',
            new_name='sync_engine_branch__82717e_idx',
            old_name='sync_engine_branch__3b5d28_idx',
        ),
        migrations.RenameIndex(
            model_name='syncevent',
            new_name='sync_engine_branch__9b44fc_idx',
            old_name='sync_engine_branch__6c0f8a_idx',
        ),
        migrations.RenameIndex(
            model_name='syncevent',
            new_name='sync_engine_device__1a3d07_idx',
            old_name='sync_engine_device__2776df_idx',
        ),
        migrations.RenameIndex(
            model_name='syncevent',
            new_name='sync_engine_branch__acc5fe_idx',
            old_name='sync_engine_branch__50f7a2_idx',
        ),
    ]
