# Generated by Django 6.0.1 on 2026-01-25 08:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tenants', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.UUIDField(db_column='ACCOUNT_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.TextField(db_column='CODE')),
                ('name', models.TextField(db_column='NAME')),
                ('account_type', models.TextField(blank=True, db_column='TYPE', null=True)),
            ],
            options={
                'db_table': 'ACCOUNTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('period_id', models.UUIDField(db_column='PERIOD_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='NAME', null=True)),
                ('start_date', models.DateField(blank=True, db_column='START_DATE', null=True)),
                ('end_date', models.DateField(blank=True, db_column='END_DATE', null=True)),
                ('is_closed', models.BooleanField(db_column='IS_CLOSED', default=False)),
            ],
            options={
                'db_table': 'ACCOUNTING_PERIODS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('audit_id', models.UUIDField(db_column='AUDIT_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('table_name', models.TextField(blank=True, db_column='TABLE_NAME', null=True)),
                ('record_id', models.UUIDField(blank=True, db_column='RECORD_ID', null=True)),
                ('action', models.TextField(blank=True, db_column='ACTION', null=True)),
                ('old_values', models.JSONField(blank=True, db_column='OLD_VALUES', null=True)),
                ('new_values', models.JSONField(blank=True, db_column='NEW_VALUES', null=True)),
                ('changed_by', models.UUIDField(blank=True, db_column='CHANGED_BY', null=True)),
                ('changed_at', models.DateTimeField(blank=True, db_column='CHANGED_AT', default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'AUDITS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionPlan',
            fields=[
                ('plan_id', models.UUIDField(db_column='PLAN_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='NAME', null=True)),
                ('target_amount', models.DecimalField(blank=True, db_column='TARGET_AMOUNT', decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'COMMISSION_PLAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('rate_id', models.UUIDField(db_column='RATE_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(blank=True, db_column='PERCENTAGE', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'COMMISSION_RATE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DebugLog',
            fields=[
                ('log_id', models.UUIDField(db_column='LOG_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, db_column='MESSAGE', null=True)),
                ('error_code', models.TextField(blank=True, db_column='ERROR_CODE', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='CREATED_AT', default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'DEBUG_LOG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeAttendanceRegister',
            fields=[
                ('attendance_id', models.UUIDField(db_column='ATTENDANCE_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField(blank=True, db_column='CHECK_IN', null=True)),
                ('check_out', models.DateTimeField(blank=True, db_column='CHECK_OUT', null=True)),
            ],
            options={
                'db_table': 'TIME_ATTENDANCE_REGISTER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionAccountingLine',
            fields=[
                ('acc_line_id', models.UUIDField(db_column='ACC_LINE_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('debit', models.DecimalField(db_column='DEBIT', decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(db_column='CREDIT', decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'TRANSACTION_ACCOUNTING_LINES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountFullReconcile',
            fields=[
                ('full_id', models.UUIDField(db_column='FULL_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ACCOUNT_FULL_RECONCILES',
            },
        ),
        migrations.CreateModel(
            name='AccountJournal',
            fields=[
                ('journal_id', models.UUIDField(db_column='JOURNAL_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.TextField(db_column='CODE')),
                ('name', models.TextField(db_column='NAME')),
                ('journal_type', models.TextField(db_column='JOURNAL_TYPE')),
                ('sequence_prefix', models.TextField(blank=True, db_column='SEQUENCE_PREFIX', null=True)),
                ('next_number', models.IntegerField(db_column='NEXT_NUMBER', default=1)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='CREATED_AT', default=django.utils.timezone.now, null=True)),
                ('subsidiary', models.ForeignKey(blank=True, db_column='SUBSIDIARY_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants.subsidiary')),
            ],
            options={
                'db_table': 'ACCOUNT_JOURNALS',
            },
        ),
        migrations.CreateModel(
            name='AccountDefaults',
            fields=[
                ('default_id', models.UUIDField(db_column='DEFAULT_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, db_column='CREATED_AT', default=django.utils.timezone.now, null=True)),
                ('cash_account', models.ForeignKey(blank=True, db_column='CASH_ACCOUNT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='defaults_cash_account', to='accounting.account')),
                ('discount_account', models.ForeignKey(blank=True, db_column='DISCOUNT_ACCOUNT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='defaults_discount_account', to='accounting.account')),
                ('receivable_account', models.ForeignKey(blank=True, db_column='RECEIVABLE_ACCOUNT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='defaults_receivable_account', to='accounting.account')),
                ('sales_account', models.ForeignKey(db_column='SALES_ACCOUNT_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='defaults_sales_account', to='accounting.account')),
                ('subsidiary', models.ForeignKey(db_column='SUBSIDIARY_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='tenants.subsidiary')),
                ('tax_account', models.ForeignKey(blank=True, db_column='TAX_ACCOUNT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='defaults_tax_account', to='accounting.account')),
                ('sales_journal', models.ForeignKey(blank=True, db_column='SALES_JOURNAL_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.accountjournal')),
            ],
            options={
                'db_table': 'ACCOUNT_DEFAULTS',
            },
        ),
        migrations.CreateModel(
            name='AccountMove',
            fields=[
                ('move_id', models.UUIDField(db_column='MOVE_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('move_number', models.TextField(db_column='MOVE_NUMBER')),
                ('move_date', models.DateField(db_column='MOVE_DATE', default=django.utils.timezone.localdate)),
                ('ref', models.TextField(blank=True, db_column='REF', null=True)),
                ('state', models.TextField(db_column='STATE', default='draft')),
                ('created_by', models.UUIDField(blank=True, db_column='CREATED_BY', null=True)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT', default=django.utils.timezone.now)),
                ('posted_at', models.DateTimeField(blank=True, db_column='POSTED_AT', null=True)),
                ('total_debit', models.DecimalField(db_column='TOTAL_DEBIT', decimal_places=2, default=0, max_digits=18)),
                ('total_credit', models.DecimalField(db_column='TOTAL_CREDIT', decimal_places=2, default=0, max_digits=18)),
                ('amount_total', models.DecimalField(db_column='AMOUNT_TOTAL', decimal_places=2, default=0, max_digits=18)),
                ('currency', models.ForeignKey(blank=True, db_column='CURRENCY_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants.currency')),
                ('journal', models.ForeignKey(db_column='JOURNAL_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.accountjournal')),
                ('period', models.ForeignKey(blank=True, db_column='PERIOD_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.accountingperiod')),
                ('subsidiary', models.ForeignKey(db_column='SUBSIDIARY_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='tenants.subsidiary')),
                ('transaction', models.ForeignKey(blank=True, db_column='TRANSACTION_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction')),
            ],
            options={
                'db_table': 'ACCOUNT_MOVES',
            },
        ),
        migrations.CreateModel(
            name='AccountMoveLine',
            fields=[
                ('line_id', models.UUIDField(db_column='LINE_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, db_column='LABEL', null=True)),
                ('debit', models.DecimalField(db_column='DEBIT', decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(db_column='CREDIT', decimal_places=2, default=0, max_digits=18)),
                ('amount_currency', models.DecimalField(blank=True, db_column='AMOUNT_CURRENCY', decimal_places=2, max_digits=18, null=True)),
                ('maturity_date', models.DateField(blank=True, db_column='MATURITY_DATE', null=True)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT', default=django.utils.timezone.now)),
                ('account', models.ForeignKey(db_column='ACCOUNT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.account')),
                ('currency', models.ForeignKey(blank=True, db_column='CURRENCY_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants.currency')),
                ('customer', models.ForeignKey(blank=True, db_column='CUSTOMER_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
                ('move', models.ForeignKey(db_column='MOVE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.accountmove')),
            ],
            options={
                'db_table': 'ACCOUNT_MOVE_LINES',
            },
        ),
        migrations.CreateModel(
            name='AccountFullReconcileLine',
            fields=[
                ('line_id', models.UUIDField(db_column='LINE_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('full_reconcile', models.ForeignKey(db_column='FULL_ID', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.accountfullreconcile')),
                ('move_line', models.ForeignKey(db_column='MOVE_LINE_ID', on_delete=django.db.models.deletion.CASCADE, to='accounting.accountmoveline')),
            ],
            options={
                'db_table': 'ACCOUNT_FULL_RECONCILE_LINES',
            },
        ),
        migrations.CreateModel(
            name='AccountPartialReconcile',
            fields=[
                ('partial_id', models.UUIDField(db_column='PARTIAL_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='AMOUNT', decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT', default=django.utils.timezone.now)),
                ('credit_move_line', models.ForeignKey(db_column='CREDIT_MOVE_LINE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='partial_credits', to='accounting.accountmoveline')),
                ('debit_move_line', models.ForeignKey(db_column='DEBIT_MOVE_LINE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='partial_debits', to='accounting.accountmoveline')),
            ],
            options={
                'db_table': 'ACCOUNT_PARTIAL_RECONCILES',
            },
        ),
        migrations.CreateModel(
            name='AccountPayment',
            fields=[
                ('payment_id', models.UUIDField(db_column='PAYMENT_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('payment_date', models.DateField(db_column='PAYMENT_DATE', default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(db_column='AMOUNT', decimal_places=2, max_digits=18)),
                ('payment_type', models.TextField(db_column='PAYMENT_TYPE')),
                ('partner_type', models.TextField(blank=True, db_column='PARTNER_TYPE', null=True)),
                ('state', models.TextField(db_column='STATE', default='draft')),
                ('reference', models.TextField(blank=True, db_column='REFERENCE', null=True)),
                ('created_at', models.DateTimeField(db_column='CREATED_AT', default=django.utils.timezone.now)),
                ('posted_at', models.DateTimeField(blank=True, db_column='POSTED_AT', null=True)),
                ('currency', models.ForeignKey(blank=True, db_column='CURRENCY_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants.currency')),
                ('customer', models.ForeignKey(blank=True, db_column='CUSTOMER_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
                ('journal', models.ForeignKey(db_column='JOURNAL_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.accountjournal')),
                ('move', models.ForeignKey(blank=True, db_column='MOVE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountmove')),
                ('subsidiary', models.ForeignKey(db_column='SUBSIDIARY_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='tenants.subsidiary')),
                ('transaction', models.ForeignKey(blank=True, db_column='TRANSACTION_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction')),
            ],
            options={
                'db_table': 'ACCOUNT_PAYMENTS',
            },
        ),
        migrations.CreateModel(
            name='AccountTax',
            fields=[
                ('tax_id', models.UUIDField(db_column='TAX_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='NAME')),
                ('tax_type', models.TextField(db_column='TAX_TYPE', default='percent')),
                ('amount', models.DecimalField(db_column='AMOUNT', decimal_places=4, default=0, max_digits=7)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('account', models.ForeignKey(blank=True, db_column='ACCOUNT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.account')),
                ('subsidiary', models.ForeignKey(blank=True, db_column='SUBSIDIARY_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants.subsidiary')),
            ],
            options={
                'db_table': 'ACCOUNT_TAXES',
            },
        ),
        migrations.CreateModel(
            name='AccountMoveLineTax',
            fields=[
                ('line_tax_id', models.UUIDField(db_column='LINE_TAX_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('move_line', models.ForeignKey(db_column='LINE_ID', on_delete=django.db.models.deletion.CASCADE, to='accounting.accountmoveline')),
                ('tax', models.ForeignKey(db_column='TAX_ID', on_delete=django.db.models.deletion.CASCADE, to='accounting.accounttax')),
            ],
            options={
                'db_table': 'ACCOUNT_MOVE_LINE_TAXES',
            },
        ),
        migrations.CreateModel(
            name='AccountTaxGroup',
            fields=[
                ('group_id', models.UUIDField(db_column='GROUP_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='NAME')),
                ('code', models.TextField(blank=True, db_column='CODE', null=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('subsidiary', models.ForeignKey(blank=True, db_column='SUBSIDIARY_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants.subsidiary')),
            ],
            options={
                'db_table': 'ACCOUNT_TAX_GROUPS',
            },
        ),
        migrations.AddField(
            model_name='accounttax',
            name='group',
            field=models.ForeignKey(blank=True, db_column='GROUP_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.accounttaxgroup'),
        ),
        migrations.CreateModel(
            name='AccountTaxTag',
            fields=[
                ('tag_id', models.UUIDField(db_column='TAG_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='NAME')),
                ('code', models.TextField(blank=True, db_column='CODE', null=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('subsidiary', models.ForeignKey(blank=True, db_column='SUBSIDIARY_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tenants.subsidiary')),
            ],
            options={
                'db_table': 'ACCOUNT_TAX_TAGS',
            },
        ),
        migrations.CreateModel(
            name='AccountTaxTagRel',
            fields=[
                ('rel_id', models.UUIDField(db_column='REL_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tag', models.ForeignKey(db_column='TAG_ID', on_delete=django.db.models.deletion.CASCADE, to='accounting.accounttaxtag')),
                ('tax', models.ForeignKey(db_column='TAX_ID', on_delete=django.db.models.deletion.CASCADE, to='accounting.accounttax')),
            ],
            options={
                'db_table': 'ACCOUNT_TAX_TAG_REL',
            },
        ),
        migrations.AddIndex(
            model_name='accountjournal',
            index=models.Index(fields=['subsidiary', 'code'], name='idx_journal_sub_code'),
        ),
        migrations.AddIndex(
            model_name='accountjournal',
            index=models.Index(fields=['journal_type'], name='idx_journal_type'),
        ),
        migrations.AddConstraint(
            model_name='accountjournal',
            constraint=models.UniqueConstraint(fields=('subsidiary', 'code'), name='uq_journal_sub_code'),
        ),
        migrations.AddConstraint(
            model_name='accountdefaults',
            constraint=models.UniqueConstraint(fields=('subsidiary',), name='uq_account_defaults_sub'),
        ),
        migrations.AddIndex(
            model_name='accountmove',
            index=models.Index(fields=['subsidiary', 'move_date'], name='idx_move_sub_date'),
        ),
        migrations.AddIndex(
            model_name='accountmove',
            index=models.Index(fields=['journal', 'move_date'], name='idx_move_journal_date'),
        ),
        migrations.AddIndex(
            model_name='accountmove',
            index=models.Index(fields=['state', 'move_date'], name='idx_move_state_date'),
        ),
        migrations.AddConstraint(
            model_name='accountmove',
            constraint=models.UniqueConstraint(fields=('journal', 'move_number'), name='uq_move_journal_number'),
        ),
        migrations.AddIndex(
            model_name='accountmoveline',
            index=models.Index(fields=['account', 'move'], name='idx_line_account_move'),
        ),
        migrations.AddIndex(
            model_name='accountmoveline',
            index=models.Index(fields=['customer'], name='idx_line_customer'),
        ),
        migrations.AddIndex(
            model_name='accountmoveline',
            index=models.Index(fields=['maturity_date'], name='idx_line_maturity'),
        ),
        migrations.AddConstraint(
            model_name='accountfullreconcileline',
            constraint=models.UniqueConstraint(fields=('full_reconcile', 'move_line'), name='uq_full_reconcile_line'),
        ),
        migrations.AddIndex(
            model_name='accountpayment',
            index=models.Index(fields=['subsidiary', 'payment_date'], name='idx_pay_sub_date'),
        ),
        migrations.AddIndex(
            model_name='accountpayment',
            index=models.Index(fields=['journal', 'payment_date'], name='idx_pay_journal_date'),
        ),
        migrations.AddIndex(
            model_name='accountpayment',
            index=models.Index(fields=['state'], name='idx_pay_state'),
        ),
        migrations.AddConstraint(
            model_name='accountmovelinetax',
            constraint=models.UniqueConstraint(fields=('move_line', 'tax'), name='uq_line_tax'),
        ),
        migrations.AddIndex(
            model_name='accounttaxgroup',
            index=models.Index(fields=['subsidiary', 'code'], name='idx_tax_group_sub'),
        ),
        migrations.AddIndex(
            model_name='accounttax',
            index=models.Index(fields=['subsidiary', 'tax_type'], name='idx_tax_sub_type'),
        ),
        migrations.AddConstraint(
            model_name='accounttaxtagrel',
            constraint=models.UniqueConstraint(fields=('tax', 'tag'), name='uq_tax_tag_rel'),
        ),
    ]
