# Generated by Django 6.0.2 on 2026-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_integrations_pickup_window'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='externalorder',
            new_name='pos_externa_branch__f024c3_idx',
            old_name='pos_extern_branch__395b70_idx',
        ),
        migrations.RenameIndex(
            model_name='externalorder',
            new_name='pos_externa_branch__ac9226_idx',
            old_name='pos_extern_branch__6ef0b2_idx',
        ),
        migrations.RenameIndex(
            model_name='externaloutboundtask',
            new_name='pos_externa_status_d1d097_idx',
            old_name='pos_extern_status_8f4b0e_idx',
        ),
        migrations.RenameIndex(
            model_name='posorder',
            new_name='pos_posorde_branch__c8eaa6_idx',
            old_name='pos_posorde_branch__2a8d77_idx',
        ),
        migrations.AlterField(
            model_name='orderchannel',
            name='code',
            field=models.CharField(choices=[('dine_in', 'dine_in'), ('takeaway', 'takeaway'), ('pickup', 'pickup'), ('pickup_window', 'pickup_window'), ('delivery', 'delivery'), ('preorder', 'preorder')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('canceled', 'canceled'), ('paid', 'paid'), ('refunded', 'refunded'), ('completed', 'completed')], default='draft', max_length=16),
        ),
    ]
