# Generated by Django 6.0.2 on 2026-02-12 19:10

import uuid

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0003_rename_pos_extern_branch__395b70_idx_pos_externa_branch__f024c3_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posorder",
            name="held_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posorder",
            name="is_held",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("job_type", models.CharField(choices=[("receipt", "receipt"), ("kitchen", "kitchen")], default="receipt", max_length=32)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("pending", "pending"), ("sent", "sent"), ("failed", "failed")], default="pending", max_length=16)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="print_jobs", to="pos.device")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="print_jobs", to="pos.posorder")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
