# Generated by Django 6.0.2 on 2026-02-12 20:20

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0004_posorder_hold_printjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="requires_opening_cash",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="printjob",
            name="order",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="print_jobs", to="pos.posorder"),
        ),
        migrations.CreateModel(
            name="DeviceHealthCheck",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("overall_status", models.CharField(choices=[("pass", "pass"), ("warn", "warn"), ("fail", "fail")], default="pass", max_length=8)),
                ("checks", models.JSONField(blank=True, default=list)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="device_checks", to="pos.branch")),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="device_checks", to="pos.device")),
                ("shift", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="device_checks", to="pos.shift")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="devicehealthcheck",
            index=models.Index(fields=["branch", "created_at"], name="pos_deviceh_branch__f7c119_idx"),
        ),
        migrations.AddIndex(
            model_name="devicehealthcheck",
            index=models.Index(fields=["device", "created_at"], name="pos_deviceh_device__559a7a_idx"),
        ),
    ]
