# Generated by Django 6.0.2 on 2026-02-18 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_order_payment_shift'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicehealthcheck',
            new_name='pos_deviceh_branch__0f9c17_idx',
            old_name='pos_deviceh_branch__f7c119_idx',
        ),
        migrations.RenameIndex(
            model_name='devicehealthcheck',
            new_name='pos_deviceh_device__7032e3_idx',
            old_name='pos_deviceh_device__559a7a_idx',
        ),
    ]
