# Generated by Django 6.0.1 on 2026-02-20

import decimal
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0011_posorder_kitchen_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErpOffer",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("external_id", models.CharField(max_length=128)),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, default="", max_length=512)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "percent"), ("fixed", "fixed")],
                        default="percent",
                        max_length=16,
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("min_order_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("max_discount_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("stackable", models.BooleanField(default=False)),
                ("applies_to", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "branch",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="erp_offers", to="pos.branch"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["branch", "is_active"], name="pos_erpoffe_branch__0138d5_idx"),
                    models.Index(fields=["branch", "last_synced_at"], name="pos_erpoffe_branch__ee7a0c_idx"),
                ],
                "unique_together": {("branch", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="ErpCoupon",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("external_id", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, default="", max_length=512)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "percent"), ("fixed", "fixed")],
                        default="percent",
                        max_length=16,
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("min_order_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("max_discount_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("usage_limit", models.PositiveIntegerField(default=0)),
                ("per_customer_limit", models.PositiveIntegerField(default=0)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "branch",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="erp_coupons", to="pos.branch"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["branch", "is_active"], name="pos_erpcoup_branch__d7f683_idx"),
                    models.Index(fields=["branch", "code"], name="pos_erpcoup_branch__57129d_idx"),
                    models.Index(fields=["branch", "last_synced_at"], name="pos_erpcoup_branch__f02565_idx"),
                ],
                "unique_together": {("branch", "code"), ("branch", "external_id")},
            },
        ),
    ]
