# Generated by Django 6.0.1 on 2026-02-09 08:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxItem',
            fields=[
                ('tax_item_id', models.UUIDField(db_column='TAX_ITEM_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(db_column='RATE', decimal_places=2, default=15, max_digits=5)),
            ],
            options={
                'db_table': 'TAX_ITEMS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxSaDocument',
            fields=[
                ('doc_id', models.UUIDField(db_column='DOC_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('xml_content', models.TextField(blank=True, db_column='XML_CONTENT', null=True)),
                ('hash_value', models.TextField(blank=True, db_column='HASH', null=True)),
                ('qr_code', models.TextField(blank=True, db_column='QR_CODE', null=True)),
                ('zatca_status', models.TextField(blank=True, db_column='ZATCA_STATUS', null=True)),
            ],
            options={
                'db_table': 'TAX_SA_DOCUMENTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxSaSetting',
            fields=[
                ('setting_id', models.UUIDField(db_column='SETTING_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('street_name', models.TextField(blank=True, db_column='STREET_NAME', null=True)),
                ('building_number', models.TextField(blank=True, db_column='BUILDING_NUMBER', null=True)),
                ('plot_identification', models.TextField(blank=True, db_column='PLOT_IDENTIFICATION', null=True)),
                ('city_subdivision', models.TextField(blank=True, db_column='CITY_SUBDIVISION', null=True)),
                ('postal_zone', models.TextField(blank=True, db_column='POSTAL_ZONE', null=True)),
            ],
            options={
                'db_table': 'TAX_SA_SETTINGS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('tax_type_id', models.UUIDField(db_column='TAX_TYPE_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='NAME', null=True)),
                ('code', models.TextField(blank=True, db_column='CODE', null=True)),
            ],
            options={
                'db_table': 'TAX_TYPES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZatcaOnboarding',
            fields=[
                ('onboard_id', models.UUIDField(db_column='ONBOARD_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('csr', models.TextField(blank=True, db_column='CSR', null=True)),
                ('csid', models.TextField(blank=True, db_column='CSID', null=True)),
                ('private_key', models.TextField(blank=True, db_column='PRIVATE_KEY', null=True)),
                ('status', models.TextField(blank=True, db_column='STATUS', null=True)),
            ],
            options={
                'db_table': 'ZATCA_ONBOARDING',
                'managed': False,
            },
        ),
    ]
