# Generated by Django 6.0.1 on 2026-01-25 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(db_column='CUSTOMER_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='NAME')),
                ('phone', models.TextField(blank=True, db_column='PHONE', null=True)),
                ('email', models.TextField(blank=True, db_column='EMAIL', null=True)),
                ('vat_number', models.TextField(blank=True, db_column='VAT_NUMBER', null=True)),
            ],
            options={
                'db_table': 'CUSTOMERS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.UUIDField(db_column='DISCOUNT_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.TextField(blank=True, db_column='CODE', null=True)),
                ('discount_type', models.TextField(blank=True, db_column='TYPE', null=True)),
                ('value', models.DecimalField(blank=True, db_column='VALUE', decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'DISCOUNTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountPolicy',
            fields=[
                ('policy_id', models.UUIDField(db_column='POLICY_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='NAME', null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='IS_ACTIVE', null=True)),
            ],
            options={
                'db_table': 'DISCOUNT_POLICIES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RewardPoint',
            fields=[
                ('reward_id', models.UUIDField(db_column='REWARD_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('points_balance', models.IntegerField(db_column='POINTS_BALANCE', default=0)),
                ('last_updated', models.DateTimeField(blank=True, db_column='LAST_UPDATED', null=True)),
            ],
            options={
                'db_table': 'REWARD_POINTS',
                'managed': False,
            },
        ),
    ]
