# Generated by Django 6.0.2 on 2026-02-18 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='configdraft',
            new_name='config_engi_company_f2657e_idx',
            old_name='config_engin_company_3152df_idx',
        ),
        migrations.RenameIndex(
            model_name='configdraft',
            new_name='config_engi_branch__1010f6_idx',
            old_name='config_engin_branch__db9f58_idx',
        ),
        migrations.RenameIndex(
            model_name='configrelease',
            new_name='config_engi_branch__922cb5_idx',
            old_name='config_engin_branch__9de267_idx',
        ),
        migrations.RenameIndex(
            model_name='configrelease',
            new_name='config_engi_branch__c11f0f_idx',
            old_name='config_engin_branch__7306e5_idx',
        ),
        migrations.RenameIndex(
            model_name='effectiveconfigsnapshot',
            new_name='config_engi_branch__606f6f_idx',
            old_name='config_engin_branch__d975f2_idx',
        ),
        migrations.RenameIndex(
            model_name='featureflag',
            new_name='config_engi_company_5404fa_idx',
            old_name='config_engin_company_3f713f_idx',
        ),
        migrations.RenameIndex(
            model_name='featureflag',
            new_name='config_engi_priorit_f0050f_idx',
            old_name='config_engin_priorit_5395d1_idx',
        ),
        migrations.RenameIndex(
            model_name='ruledefinition',
            new_name='config_engi_company_c2bdc4_idx',
            old_name='config_engin_company_f52600_idx',
        ),
        migrations.RenameIndex(
            model_name='ruledefinition',
            new_name='config_engi_priorit_18244e_idx',
            old_name='config_engin_priorit_e95c0d_idx',
        ),
    ]
