# Generated by Django 6.0.1 on 2026-02-09 08:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_id', models.UUIDField(db_column='BIN_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bin_code', models.TextField(blank=True, db_column='BIN_CODE', null=True)),
            ],
            options={
                'db_table': 'BINS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionInventoryBatch',
            fields=[
                ('batch_id', models.UUIDField(db_column='BATCH_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('batch_number', models.TextField(db_column='BATCH_NUMBER')),
                ('expiry_date', models.DateField(blank=True, db_column='EXPIRY_DATE', null=True)),
                ('quantity', models.DecimalField(blank=True, db_column='QUANTITY', decimal_places=3, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'TRANSACTION_INVENTORY_BATCH',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionInventoryDetail',
            fields=[
                ('detail_id', models.UUIDField(db_column='DETAIL_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity_on_hand', models.DecimalField(db_column='QUANTITY_ON_HAND', decimal_places=3, default=0, max_digits=12)),
                ('reserved_quantity', models.DecimalField(db_column='RESERVED_QUANTITY', decimal_places=3, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(blank=True, db_column='LAST_UPDATED', default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'TRANSACTION_INVENTORY_DETAILS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='XxItemSerialNumber',
            fields=[
                ('serial_id', models.UUIDField(db_column='SERIAL_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('serial_number', models.TextField(db_column='SERIAL_NUMBER')),
                ('status', models.TextField(blank=True, db_column='STATUS', null=True)),
            ],
            options={
                'db_table': 'XX_ITEM_SERIAL_NUMBER',
                'managed': False,
            },
        ),
    ]
