# Generated by Django 6.0.1 on 2026-02-09 08:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FndLoginLog',
            fields=[
                ('log_id', models.UUIDField(db_column='LOG_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(blank=True, db_column='LOGIN_TIME', default=django.utils.timezone.now, null=True)),
                ('ip_address', models.TextField(blank=True, db_column='IP_ADDRESS', null=True)),
                ('device_info', models.TextField(blank=True, db_column='DEVICE_INFO', null=True)),
            ],
            options={
                'db_table': 'FND_LOGIN_LOGS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FndResponsibility',
            fields=[
                ('responsibility_id', models.UUIDField(db_column='RESPONSIBILITY_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.TextField(db_column='CODE', unique=True)),
                ('name', models.TextField(blank=True, db_column='NAME', null=True)),
            ],
            options={
                'db_table': 'FND_RESPONSIBILITES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FndRole',
            fields=[
                ('role_id', models.UUIDField(db_column='ROLE_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('role_name', models.TextField(db_column='ROLE_NAME')),
                ('description', models.TextField(blank=True, db_column='DESCRIPTION', null=True)),
            ],
            options={
                'db_table': 'FND_ROLES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FndUser',
            fields=[
                ('user_id', models.UUIDField(db_column='USER_ID', primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, db_column='USERNAME', null=True)),
                ('full_name', models.TextField(blank=True, db_column='FULL_NAME', null=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='CREATED_AT', default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'FND_USERS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FndRoleResponsibility',
            fields=[
                ('role', models.ForeignKey(db_column='ROLE_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='security.fndrole')),
            ],
            options={
                'db_table': 'FND_ROLES_RESPONSIBILITIES',
                'managed': False,
            },
        ),
    ]
