# Generated by Django 6.0.1 on 2026-02-09 08:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FndReportParameter',
            fields=[
                ('param_id', models.UUIDField(db_column='PARAM_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('report_name', models.TextField(blank=True, db_column='REPORT_NAME', null=True)),
                ('param_key', models.TextField(blank=True, db_column='PARAM_KEY', null=True)),
                ('param_label', models.TextField(blank=True, db_column='PARAM_LABEL', null=True)),
            ],
            options={
                'db_table': 'FND_REPORT_PARAMETERS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VDailySalesSummary',
            fields=[
                ('subsidiary_id', models.UUIDField(db_column='SUBSIDIARY_ID', primary_key=True, serialize=False)),
                ('branch_name', models.TextField(db_column='BRANCH_NAME')),
                ('sale_date', models.DateField(db_column='SALE_DATE')),
                ('total_invoices', models.BigIntegerField(db_column='TOTAL_INVOICES')),
                ('total_revenue', models.DecimalField(db_column='TOTAL_REVENUE', decimal_places=2, max_digits=18)),
                ('total_vat', models.DecimalField(db_column='TOTAL_VAT', decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'V_DAILY_SALES_SUMMARY',
                'managed': False,
            },
        ),
    ]
