# Generated by Django 6.0.1 on 2026-01-25 08:29

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('method_id', models.UUIDField(db_column='METHOD_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='NAME')),
            ],
            options={
                'db_table': 'PAYMENT_METHODS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(db_column='TRANSACTION_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('trx_number', models.TextField(db_column='TRX_NUMBER')),
                ('trx_date', models.DateTimeField(blank=True, db_column='TRX_DATE', default=django.utils.timezone.now, null=True)),
                ('total_amount', models.DecimalField(db_column='TOTAL_AMOUNT', decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(db_column='TOTAL_TAX', decimal_places=2, default=0, max_digits=12)),
                ('total_discount', models.DecimalField(db_column='TOTAL_DISCOUNT', decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, db_column='NOTES', null=True)),
            ],
            options={
                'db_table': 'TRANSACTIONS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionComment',
            fields=[
                ('comment_id', models.UUIDField(db_column='COMMENT_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('comment_text', models.TextField(blank=True, db_column='COMMENT_TEXT', null=True)),
            ],
            options={
                'db_table': 'TRANSACTION_COMMENTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('line_id', models.UUIDField(db_column='LINE_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(db_column='QUANTITY', decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(db_column='UNIT_PRICE', decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(db_column='DISCOUNT_AMOUNT', decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(db_column='TAX_AMOUNT', decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(blank=True, db_column='LINE_TOTAL', decimal_places=2, editable=False, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'TRANSACTION_LINES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('status_id', models.UUIDField(db_column='STATUS_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.TextField(db_column='CODE')),
                ('name', models.TextField(blank=True, db_column='NAME', null=True)),
            ],
            options={
                'db_table': 'TRANSACTION_STATUS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionTaxDetail',
            fields=[
                ('tax_detail_id', models.UUIDField(db_column='TAX_DETAIL_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('taxable_amount', models.DecimalField(blank=True, db_column='TAXABLE_AMOUNT', decimal_places=2, max_digits=12, null=True)),
                ('tax_amount', models.DecimalField(blank=True, db_column='TAX_AMOUNT', decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'TRANSACTION_TAX_DETAILS',
                'managed': False,
            },
        ),
    ]
