# Generated by Django 6.0.2 on 2026-02-18 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflowdefinition',
            new_name='workflow_wo_company_2f98a1_idx',
            old_name='workflow_wo_company_c74c35_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowdefinition',
            new_name='workflow_wo_priorit_69218e_idx',
            old_name='workflow_wo_priorit_8f4ca8_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowexecution',
            new_name='workflow_wo_branch__677ac8_idx',
            old_name='workflow_wo_branch__1f40e7_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowexecution',
            new_name='workflow_wo_status_c231ff_idx',
            old_name='workflow_wo_status_2b3212_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowsteplog',
            new_name='workflow_wo_executi_9a774b_idx',
            old_name='workflow_wo_executi_9fa5a0_idx',
        ),
    ]
